//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.AssetsTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssetTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.AssetsTr.AssetTr", typeof(AssetTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new asset.
        /// </summary>
        public static string AddNewAsset {
            get {
                return ResourceManager.GetString("AddNewAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset details.
        /// </summary>
        public static string AssetDetails {
            get {
                return ResourceManager.GetString("AssetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset information was updated..
        /// </summary>
        public static string AssetInfoWasUpdated {
            get {
                return ResourceManager.GetString("AssetInfoWasUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset is not active..
        /// </summary>
        public static string AssetIsNotActive {
            get {
                return ResourceManager.GetString("AssetIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset was acquired..
        /// </summary>
        public static string AssetWasAcquired {
            get {
                return ResourceManager.GetString("AssetWasAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset was part of asset order ! The location, site or user can be changed !&quot;.
        /// </summary>
        public static string AssetWasPartOfOrder {
            get {
                return ResourceManager.GetString("AssetWasPartOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset was relocated..
        /// </summary>
        public static string AssetWasRelocated {
            get {
                return ResourceManager.GetString("AssetWasRelocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset was renovated..
        /// </summary>
        public static string AssetWasRenovated {
            get {
                return ResourceManager.GetString("AssetWasRenovated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset was scrapped..
        /// </summary>
        public static string AssetWasScrapped {
            get {
                return ResourceManager.GetString("AssetWasScrapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Brand&quot; is required..
        /// </summary>
        public static string BrandIsRequired {
            get {
                return ResourceManager.GetString("BrandIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose location.
        /// </summary>
        public static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose site.
        /// </summary>
        public static string ChooseSite {
            get {
                return ResourceManager.GetString("ChooseSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose user.
        /// </summary>
        public static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Currecy&quot;is required..
        /// </summary>
        public static string CurrencyIsRequired {
            get {
                return ResourceManager.GetString("CurrencyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of manufacture.
        /// </summary>
        public static string DateOfManufacture {
            get {
                return ResourceManager.GetString("DateOfManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a asset with the same Inventory number..
        /// </summary>
        public static string ExistAssetWithIN {
            get {
                return ResourceManager.GetString("ExistAssetWithIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantee.
        /// </summary>
        public static string Guarantee {
            get {
                return ResourceManager.GetString("Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered must be positive number..
        /// </summary>
        public static string GuaranteeRangeError {
            get {
                return ResourceManager.GetString("GuaranteeRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory number.
        /// </summary>
        public static string InventoryNumber {
            get {
                return ResourceManager.GetString("InventoryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Inventory number&quot;is required..
        /// </summary>
        public static string InventoryNumberIsRequired {
            get {
                return ResourceManager.GetString("InventoryNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location code.
        /// </summary>
        public static string LocationCode {
            get {
                return ResourceManager.GetString("LocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Model&quot;is required..
        /// </summary>
        public static string ModelIsRequired {
            get {
                return ResourceManager.GetString("ModelIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sites.
        /// </summary>
        public static string NoSites {
            get {
                return ResourceManager.GetString("NoSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Price&quot; is required..
        /// </summary>
        public static string PriceIsRequired {
            get {
                return ResourceManager.GetString("PriceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered must be positive number..
        /// </summary>
        public static string PriceRangeError {
            get {
                return ResourceManager.GetString("PriceRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        public static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Producer&quot;is required..
        /// </summary>
        public static string ProducerIsRequired {
            get {
                return ResourceManager.GetString("ProducerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Site&quot;is required..
        /// </summary>
        public static string SiteIsRequired {
            get {
                return ResourceManager.GetString("SiteIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Type&quot;is required..
        /// </summary>
        public static string TypeIsRequired {
            get {
                return ResourceManager.GetString("TypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
