//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.OrdersTr.AssetOrderTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssetOrderTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetOrderTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.OrdersTr.AssetOrderTr.AssetOrderTr", typeof(AssetOrderTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved assets.
        /// </summary>
        public static string ApprovedAssets {
            get {
                return ResourceManager.GetString("ApprovedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved request (Asset order).
        /// </summary>
        public static string ApprovedRequest {
            get {
                return ResourceManager.GetString("ApprovedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved requests (Asset order).
        /// </summary>
        public static string ApprovedRequests {
            get {
                return ResourceManager.GetString("ApprovedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assets are not gave!.
        /// </summary>
        public static string AssetsAreNotGave {
            get {
                return ResourceManager.GetString("AssetsAreNotGave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose assets.
        /// </summary>
        public static string ChooseAssets {
            get {
                return ResourceManager.GetString("ChooseAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of send.
        /// </summary>
        public static string DateOfSend {
            get {
                return ResourceManager.GetString("DateOfSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline a request for asset.
        /// </summary>
        public static string DeclineRequest {
            get {
                return ResourceManager.GetString("DeclineRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished request (Asset order).
        /// </summary>
        public static string FinishedRequest {
            get {
                return ResourceManager.GetString("FinishedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gave assets.
        /// </summary>
        public static string GaveAssest {
            get {
                return ResourceManager.GetString("GaveAssest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give assets.
        /// </summary>
        public static string GiveAssets {
            get {
                return ResourceManager.GetString("GiveAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is approved?.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Message&quot; is required..
        /// </summary>
        public static string MessageIsRequired {
            get {
                return ResourceManager.GetString("MessageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No approved requests !.
        /// </summary>
        public static string NoApprovedRequests {
            get {
                return ResourceManager.GetString("NoApprovedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history !.
        /// </summary>
        public static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests for approving !.
        /// </summary>
        public static string NoRequestsForApproving {
            get {
                return ResourceManager.GetString("NoRequestsForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests for finishing !.
        /// </summary>
        public static string NoRequestsForFinishing {
            get {
                return ResourceManager.GetString("NoRequestsForFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select assets.
        /// </summary>
        public static string PleaseSelectAssets {
            get {
                return ResourceManager.GetString("PleaseSelectAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for approving (Asset order).
        /// </summary>
        public static string RequestForApproving {
            get {
                return ResourceManager.GetString("RequestForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for finishing (Asset order).
        /// </summary>
        public static string RequestForFinishing {
            get {
                return ResourceManager.GetString("RequestForFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is not approved !.
        /// </summary>
        public static string RequestIsNotApproved {
            get {
                return ResourceManager.GetString("RequestIsNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for approving (Asset order).
        /// </summary>
        public static string RequestsForApproving {
            get {
                return ResourceManager.GetString("RequestsForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for finishing (Asset order).
        /// </summary>
        public static string RequestsForFinishing {
            get {
                return ResourceManager.GetString("RequestsForFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request for an asset.
        /// </summary>
        public static string SendReqForAsset {
            get {
                return ResourceManager.GetString("SendReqForAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully sent the request !.
        /// </summary>
        public static string SuccSending {
            get {
                return ResourceManager.GetString("SuccSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want assets.
        /// </summary>
        public static string WantAssets {
            get {
                return ResourceManager.GetString("WantAssets", resourceCulture);
            }
        }
    }
}
