//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.InvoiceTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.InvoiceTr.InvoiceTr", typeof(InvoiceTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acountable person.
        /// </summary>
        public static string AcountablePerson {
            get {
                return ResourceManager.GetString("AcountablePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is approved?.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill to.
        /// </summary>
        public static string BillTo {
            get {
                return ResourceManager.GetString("BillTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulstat.
        /// </summary>
        public static string Bulstat {
            get {
                return ResourceManager.GetString("Bulstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose items.
        /// </summary>
        public static string ChooseItems {
            get {
                return ResourceManager.GetString("ChooseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose order.
        /// </summary>
        public static string ChooseOrder {
            get {
                return ResourceManager.GetString("ChooseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose provider.
        /// </summary>
        public static string ChooseProvider {
            get {
                return ResourceManager.GetString("ChooseProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled user.
        /// </summary>
        public static string CompiledUser {
            get {
                return ResourceManager.GetString("CompiledUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create invoice.
        /// </summary>
        public static string CreateInvoice {
            get {
                return ResourceManager.GetString("CreateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approving date.
        /// </summary>
        public static string DateOfApproving {
            get {
                return ResourceManager.GetString("DateOfApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of issue.
        /// </summary>
        public static string DateOfCreation {
            get {
                return ResourceManager.GetString("DateOfCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of issue.
        /// </summary>
        public static string DateOfIssue {
            get {
                return ResourceManager.GetString("DateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date.
        /// </summary>
        public static string DateOfPayment {
            get {
                return ResourceManager.GetString("DateOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of send.
        /// </summary>
        public static string DateOfSend {
            get {
                return ResourceManager.GetString("DateOfSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline invoice.
        /// </summary>
        public static string DeclineInvoice {
            get {
                return ResourceManager.GetString("DeclineInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is finished?.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History invoice.
        /// </summary>
        public static string HistoryInvoice {
            get {
                return ResourceManager.GetString("HistoryInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice for approving.
        /// </summary>
        public static string InvoiceForApproving {
            get {
                return ResourceManager.GetString("InvoiceForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice for paying.
        /// </summary>
        public static string InvoiceForPaying {
            get {
                return ResourceManager.GetString("InvoiceForPaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Invoice number&quot;is required..
        /// </summary>
        public static string InvoiceNumberIsrequired {
            get {
                return ResourceManager.GetString("InvoiceNumberIsrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices for approving.
        /// </summary>
        public static string InvoicesForApproving {
            get {
                return ResourceManager.GetString("InvoicesForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices for paid.
        /// </summary>
        public static string InvoicesForPaid {
            get {
                return ResourceManager.GetString("InvoicesForPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a member of some site !.
        /// </summary>
        public static string MustMember {
            get {
                return ResourceManager.GetString("MustMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select items !.
        /// </summary>
        public static string MustSelectItems {
            get {
                return ResourceManager.GetString("MustSelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ivoices for approving !.
        /// </summary>
        public static string NoInvoicesForApproving {
            get {
                return ResourceManager.GetString("NoInvoicesForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invoices for paid !.
        /// </summary>
        public static string NoInvoicesForPaid {
            get {
                return ResourceManager.GetString("NoInvoicesForPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not approved.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not payed.
        /// </summary>
        public static string NotPayed {
            get {
                return ResourceManager.GetString("NotPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search type.
        /// </summary>
        public static string OrOrAnd {
            get {
                return ResourceManager.GetString("OrOrAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is paid?.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last date for payment.
        /// </summary>
        public static string PaymentPeriod {
            get {
                return ResourceManager.GetString("PaymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Payment period&quot;is required..
        /// </summary>
        public static string PaymentPeriodIsRequired {
            get {
                return ResourceManager.GetString("PaymentPeriodIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select items.
        /// </summary>
        public static string PleaseSelectItems {
            get {
                return ResourceManager.GetString("PleaseSelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select provider order.
        /// </summary>
        public static string PleaseSelectPO {
            get {
                return ResourceManager.GetString("PleaseSelectPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select provider.
        /// </summary>
        public static string PleaseSelectPovider {
            get {
                return ResourceManager.GetString("PleaseSelectPovider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Provider&quot; is required..
        /// </summary>
        public static string ProviderIsRequired {
            get {
                return ResourceManager.GetString("ProviderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider order.
        /// </summary>
        public static string ProviderOrder {
            get {
                return ResourceManager.GetString("ProviderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Acountable person&quot; is required..
        /// </summary>
        public static string RecipientMOLIsRequired {
            get {
                return ResourceManager.GetString("RecipientMOLIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remit to.
        /// </summary>
        public static string RemitTo {
            get {
                return ResourceManager.GetString("RemitTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a invoice with the same inventory number !.
        /// </summary>
        public static string SameInventoryNumber {
            get {
                return ResourceManager.GetString("SameInventoryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a invoice with the same number !.
        /// </summary>
        public static string SameNum {
            get {
                return ResourceManager.GetString("SameNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent email.
        /// </summary>
        public static string SentEmail {
            get {
                return ResourceManager.GetString("SentEmail", resourceCulture);
            }
        }
    }
}
