//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.RenovationTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RenovationTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RenovationTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.RenovationTr.RenovationTr", typeof(RenovationTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance.
        /// </summary>
        public static string Acceptance {
            get {
                return ResourceManager.GetString("Acceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance.
        /// </summary>
        public static string Acceptancnig {
            get {
                return ResourceManager.GetString("Acceptancnig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved request.
        /// </summary>
        public static string ApprovedRequest {
            get {
                return ResourceManager.GetString("ApprovedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved requests.
        /// </summary>
        public static string ApprovedRequests {
            get {
                return ResourceManager.GetString("ApprovedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve request for renovation.
        /// </summary>
        public static string ApproveRequestForRenovation {
            get {
                return ResourceManager.GetString("ApproveRequestForRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset cannot be renovate !.
        /// </summary>
        public static string AssetCannotBeRenovated {
            get {
                return ResourceManager.GetString("AssetCannotBeRenovated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Asset&quot; is required !.
        /// </summary>
        public static string AssetIsRequired {
            get {
                return ResourceManager.GetString("AssetIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets for renovating.
        /// </summary>
        public static string AssetsForRenovating {
            get {
                return ResourceManager.GetString("AssetsForRenovating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose asset.
        /// </summary>
        public static string ChooseAsset {
            get {
                return ResourceManager.GetString("ChooseAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create renovation request.
        /// </summary>
        public static string CreateRenovationRequest {
            get {
                return ResourceManager.GetString("CreateRenovationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline a request for renovation asset.
        /// </summary>
        public static string DeclineARequestForRenovation {
            get {
                return ResourceManager.GetString("DeclineARequestForRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give asset.
        /// </summary>
        public static string GiveAsset {
            get {
                return ResourceManager.GetString("GiveAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History requests for renovation.
        /// </summary>
        public static string HistoryRequestsForRenovation {
            get {
                return ResourceManager.GetString("HistoryRequestsForRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is approved?.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is asset renovated?.
        /// </summary>
        public static string IsAssetRenovated {
            get {
                return ResourceManager.GetString("IsAssetRenovated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is received?.
        /// </summary>
        public static string IsReceive {
            get {
                return ResourceManager.GetString("IsReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing.
        /// </summary>
        public static string Issuing {
            get {
                return ResourceManager.GetString("Issuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No approved requests !.
        /// </summary>
        public static string NoApprovedRequests {
            get {
                return ResourceManager.GetString("NoApprovedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assets for renovating !.
        /// </summary>
        public static string NoAssetsForRenovating {
            get {
                return ResourceManager.GetString("NoAssetsForRenovating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests for approving !.
        /// </summary>
        public static string NoRequestsForApproving {
            get {
                return ResourceManager.GetString("NoRequestsForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No returned assets !.
        /// </summary>
        public static string NoReturnedAssets {
            get {
                return ResourceManager.GetString("NoReturnedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem message.
        /// </summary>
        public static string ProblemMessage {
            get {
                return ResourceManager.GetString("ProblemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Problem message&quot;is required !.
        /// </summary>
        public static string ProblemMessageIsRequired {
            get {
                return ResourceManager.GetString("ProblemMessageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovate.
        /// </summary>
        public static string Renovate {
            get {
                return ResourceManager.GetString("Renovate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request details.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for renovation.
        /// </summary>
        public static string RequestForRenovation {
            get {
                return ResourceManager.GetString("RequestForRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for approving.
        /// </summary>
        public static string RequestsForApproving {
            get {
                return ResourceManager.GetString("RequestsForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned asset.
        /// </summary>
        public static string ReturnedAsset {
            get {
                return ResourceManager.GetString("ReturnedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned assets.
        /// </summary>
        public static string ReturnedAssets {
            get {
                return ResourceManager.GetString("ReturnedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select asset.
        /// </summary>
        public static string SelectAsset {
            get {
                return ResourceManager.GetString("SelectAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully sent a request for renovation of an asset..
        /// </summary>
        public static string SuccessSending {
            get {
                return ResourceManager.GetString("SuccessSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a request for renovation of this asset..
        /// </summary>
        public static string ThereIsRequestForRenovation {
            get {
                return ResourceManager.GetString("ThereIsRequestForRenovation", resourceCulture);
            }
        }
    }
}
