//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.EventsTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventsTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventsTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.EventsTr.EventsTr", typeof(EventsTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new accident to answer !.
        /// </summary>
        public static string e10 {
            get {
                return ResourceManager.GetString("e10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new answer from accident !.
        /// </summary>
        public static string e11 {
            get {
                return ResourceManager.GetString("e11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items of request with number.
        /// </summary>
        public static string e12 {
            get {
                return ResourceManager.GetString("e12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was received.
        /// </summary>
        public static string e121 {
            get {
                return ResourceManager.GetString("e121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new asset request for approving !.
        /// </summary>
        public static string e13 {
            get {
                return ResourceManager.GetString("e13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for assets with inventory numbers.
        /// </summary>
        public static string e14 {
            get {
                return ResourceManager.GetString("e14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not approved..
        /// </summary>
        public static string e141 {
            get {
                return ResourceManager.GetString("e141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new approved request for asset !.
        /// </summary>
        public static string e15 {
            get {
                return ResourceManager.GetString("e15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for assets with inventory numbers.
        /// </summary>
        public static string e16 {
            get {
                return ResourceManager.GetString("e16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was approved. But the assets cannot be gave !.
        /// </summary>
        public static string e161 {
            get {
                return ResourceManager.GetString("e161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a request for finishing!.
        /// </summary>
        public static string e17 {
            get {
                return ResourceManager.GetString("e17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new invoice for approving !.
        /// </summary>
        public static string e18 {
            get {
                return ResourceManager.GetString("e18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new invice for paying !.
        /// </summary>
        public static string e19 {
            get {
                return ResourceManager.GetString("e19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invoice was not approved !.
        /// </summary>
        public static string e20 {
            get {
                return ResourceManager.GetString("e20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invoice was payed !.
        /// </summary>
        public static string e21 {
            get {
                return ResourceManager.GetString("e21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new request for items !.
        /// </summary>
        public static string e22 {
            get {
                return ResourceManager.GetString("e22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for.
        /// </summary>
        public static string e23 {
            get {
                return ResourceManager.GetString("e23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not approved..
        /// </summary>
        public static string e231 {
            get {
                return ResourceManager.GetString("e231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new approved request for items !.
        /// </summary>
        public static string e24 {
            get {
                return ResourceManager.GetString("e24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for.
        /// </summary>
        public static string e25 {
            get {
                return ResourceManager.GetString("e25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was approved. But the items cannot be gave !.
        /// </summary>
        public static string e251 {
            get {
                return ResourceManager.GetString("e251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are new request to provider for approving!.
        /// </summary>
        public static string e26 {
            get {
                return ResourceManager.GetString("e26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to provider was not approved..
        /// </summary>
        public static string e27 {
            get {
                return ResourceManager.GetString("e27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to provider was approved..
        /// </summary>
        public static string e28 {
            get {
                return ResourceManager.GetString("e28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new requst for relocation for approving !.
        /// </summary>
        public static string e29 {
            get {
                return ResourceManager.GetString("e29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for relocate the asset with inventory number.
        /// </summary>
        public static string e30 {
            get {
                return ResourceManager.GetString("e30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was approved..
        /// </summary>
        public static string e301 {
            get {
                return ResourceManager.GetString("e301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for relocate the asset with inventory number.
        /// </summary>
        public static string e31 {
            get {
                return ResourceManager.GetString("e31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not approved..
        /// </summary>
        public static string e311 {
            get {
                return ResourceManager.GetString("e311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new asset with inventory number.
        /// </summary>
        public static string e32 {
            get {
                return ResourceManager.GetString("e32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for receiving..
        /// </summary>
        public static string e321 {
            get {
                return ResourceManager.GetString("e321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аsset with inventory number.
        /// </summary>
        public static string e33 {
            get {
                return ResourceManager.GetString("e33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was relocated..
        /// </summary>
        public static string e331 {
            get {
                return ResourceManager.GetString("e331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are new request for renovation !.
        /// </summary>
        public static string e34 {
            get {
                return ResourceManager.GetString("e34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for renovation the asset with inventory number.
        /// </summary>
        public static string e35 {
            get {
                return ResourceManager.GetString("e35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not approved..
        /// </summary>
        public static string e351 {
            get {
                return ResourceManager.GetString("e351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request for renovation was removed by user !.
        /// </summary>
        public static string e36 {
            get {
                return ResourceManager.GetString("e36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new asset for renovating !.
        /// </summary>
        public static string e37 {
            get {
                return ResourceManager.GetString("e37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your asset with inventory number.
        /// </summary>
        public static string e38 {
            get {
                return ResourceManager.GetString("e38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was renovated and now it is active !.
        /// </summary>
        public static string e381 {
            get {
                return ResourceManager.GetString("e381", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset with inventory number.
        /// </summary>
        public static string e39 {
            get {
                return ResourceManager.GetString("e39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not renovated and now is active..
        /// </summary>
        public static string e391 {
            get {
                return ResourceManager.GetString("e391", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new sccraping request for approving !.
        /// </summary>
        public static string e40 {
            get {
                return ResourceManager.GetString("e40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for scrap asset with inventory number.
        /// </summary>
        public static string e41 {
            get {
                return ResourceManager.GetString("e41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was approved..
        /// </summary>
        public static string e411 {
            get {
                return ResourceManager.GetString("e411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аsset with inventory number.
        /// </summary>
        public static string e42 {
            get {
                return ResourceManager.GetString("e42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was scrapped..
        /// </summary>
        public static string e421 {
            get {
                return ResourceManager.GetString("e421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for scrapping asset with inventory number.
        /// </summary>
        public static string e43 {
            get {
                return ResourceManager.GetString("e43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not approved..
        /// </summary>
        public static string e431 {
            get {
                return ResourceManager.GetString("e431", resourceCulture);
            }
        }
    }
}
