//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.ReportsArea {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.ReportsArea.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accident has answer.
        /// </summary>
        public static string AccHasAnswer {
            get {
                return ResourceManager.GetString("AccHasAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accident has not answer.
        /// </summary>
        public static string AccHasNotAnswer {
            get {
                return ResourceManager.GetString("AccHasNotAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Asset&quot; is required.
        /// </summary>
        public static string AssetIsRequired {
            get {
                return ResourceManager.GetString("AssetIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset relocations.
        /// </summary>
        public static string AssetRelocations {
            get {
                return ResourceManager.GetString("AssetRelocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose asset.
        /// </summary>
        public static string ChooseAsset {
            get {
                return ResourceManager.GetString("ChooseAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given date.
        /// </summary>
        public static string DateOfGiven {
            get {
                return ResourceManager.GetString("DateOfGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received date.
        /// </summary>
        public static string DateOfReceived {
            get {
                return ResourceManager.GetString("DateOfReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of reply.
        /// </summary>
        public static string DateOfReply {
            get {
                return ResourceManager.GetString("DateOfReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of send.
        /// </summary>
        public static string DateOfSend {
            get {
                return ResourceManager.GetString("DateOfSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fieled &quot;From date&quot;is required..
        /// </summary>
        public static string FromDateRequired {
            get {
                return ResourceManager.GetString("FromDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From location.
        /// </summary>
        public static string FromLocation {
            get {
                return ResourceManager.GetString("FromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From site.
        /// </summary>
        public static string FromSite {
            get {
                return ResourceManager.GetString("FromSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From user.
        /// </summary>
        public static string FromUser {
            get {
                return ResourceManager.GetString("FromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all accidents for certain dates.
        /// </summary>
        public static string GetAllAccForDate {
            get {
                return ResourceManager.GetString("GetAllAccForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all asset which are renovated between two dates.
        /// </summary>
        public static string GetAllAssetRenovated {
            get {
                return ResourceManager.GetString("GetAllAssetRenovated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all assets with certain status.
        /// </summary>
        public static string GetAllAssetsStatus {
            get {
                return ResourceManager.GetString("GetAllAssetsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all relocations for certain asset.
        /// </summary>
        public static string GetAllRelAsset {
            get {
                return ResourceManager.GetString("GetAllRelAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get invoices by dates.
        /// </summary>
        public static string GetInvoicesByDates {
            get {
                return ResourceManager.GetString("GetInvoicesByDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose at least one date !.
        /// </summary>
        public static string MustChooseAtLeastOneDate {
            get {
                return ResourceManager.GetString("MustChooseAtLeastOneDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select status.
        /// </summary>
        public static string PleaseSelStatus {
            get {
                return ResourceManager.GetString("PleaseSelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovated assets between.
        /// </summary>
        public static string RenovateAssetsBetween {
            get {
                return ResourceManager.GetString("RenovateAssetsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search type.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Status&quot; is required..
        /// </summary>
        public static string StatusIsRequired {
            get {
                return ResourceManager.GetString("StatusIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;To date&quot; is required..
        /// </summary>
        public static string ToDateRequired {
            get {
                return ResourceManager.GetString("ToDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToLocation.
        /// </summary>
        public static string ToLocation {
            get {
                return ResourceManager.GetString("ToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To site.
        /// </summary>
        public static string ToSite {
            get {
                return ResourceManager.GetString("ToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To site.
        /// </summary>
        public static string ToSiteRel {
            get {
                return ResourceManager.GetString("ToSiteRel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To user.
        /// </summary>
        public static string ToUser {
            get {
                return ResourceManager.GetString("ToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View accident.
        /// </summary>
        public static string ViewAcc {
            get {
                return ResourceManager.GetString("ViewAcc", resourceCulture);
            }
        }
    }
}
