//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.ExchangeRateTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExchangeRateTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExchangeRateTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.ExchangeRateTr.ExchangeRateTr", typeof(ExchangeRateTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new exchange rate.
        /// </summary>
        public static string AddNewExchangeRate {
            get {
                return ResourceManager.GetString("AddNewExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose currency.
        /// </summary>
        public static string ChooseCurrency {
            get {
                return ResourceManager.GetString("ChooseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a exchange rate.
        /// </summary>
        public static string EditExhangeRate {
            get {
                return ResourceManager.GetString("EditExhangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rates.
        /// </summary>
        public static string ExchangeRates {
            get {
                return ResourceManager.GetString("ExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a exchange rate for this currencies !.
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From currency.
        /// </summary>
        public static string FromCurrency {
            get {
                return ResourceManager.GetString("FromCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;From currency&quot;is required..
        /// </summary>
        public static string FromCurrencyIsRequired {
            get {
                return ResourceManager.GetString("FromCurrencyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New exchange rate.
        /// </summary>
        public static string NewExchangeRate {
            get {
                return ResourceManager.GetString("NewExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Rate&quot;is required..
        /// </summary>
        public static string RateIsRequired {
            get {
                return ResourceManager.GetString("RateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To currency.
        /// </summary>
        public static string ToCurrency {
            get {
                return ResourceManager.GetString("ToCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;To currency&quot;is required..
        /// </summary>
        public static string ToCurrencyIsRequired {
            get {
                return ResourceManager.GetString("ToCurrencyIsRequired", resourceCulture);
            }
        }
    }
}
