//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.AccidentTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccidentTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccidentTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.AccidentTr.AccidentTr", typeof(AccidentTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents with answer.
        /// </summary>
        public static string AccidentsWithAnswer {
            get {
                return ResourceManager.GetString("AccidentsWithAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents to answer.
        /// </summary>
        public static string AccidentToAnswer {
            get {
                return ResourceManager.GetString("AccidentToAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Answer&quot; is required..
        /// </summary>
        public static string AnswerFieldIsRequired {
            get {
                return ResourceManager.GetString("AnswerFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new accident.
        /// </summary>
        public static string CreateNewAccident {
            get {
                return ResourceManager.GetString("CreateNewAccident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Message&quot; is required..
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accidents to answer !.
        /// </summary>
        public static string NoAccidentsToAnswer {
            get {
                return ResourceManager.GetString("NoAccidentsToAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answers.
        /// </summary>
        public static string NoAnswers {
            get {
                return ResourceManager.GetString("NoAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully send.
        /// </summary>
        public static string SuccessfullySend {
            get {
                return ResourceManager.GetString("SuccessfullySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View accident answer.
        /// </summary>
        public static string ViewAccAnswer {
            get {
                return ResourceManager.GetString("ViewAccAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View accident to answer.
        /// </summary>
        public static string ViewAccToAnswer {
            get {
                return ResourceManager.GetString("ViewAccToAnswer", resourceCulture);
            }
        }
    }
}
