//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.OrdersTr.ProviderOrder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProviderOrderTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProviderOrderTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.OrdersTr.ProviderOrder.ProviderOrderTr", typeof(ProviderOrderTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are added offers for this request !.
        /// </summary>
        public static string AddedOffers {
            get {
                return ResourceManager.GetString("AddedOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add form for item.
        /// </summary>
        public static string AddFormForItem {
            get {
                return ResourceManager.GetString("AddFormForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add items.
        /// </summary>
        public static string AddItems {
            get {
                return ResourceManager.GetString("AddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add offers.
        /// </summary>
        public static string AddOffers {
            get {
                return ResourceManager.GetString("AddOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved offers.
        /// </summary>
        public static string ApprovedOffers {
            get {
                return ResourceManager.GetString("ApprovedOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved reqeusts (Provider order).
        /// </summary>
        public static string ApprovedRequests {
            get {
                return ResourceManager.GetString("ApprovedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Content&quot; is required!.
        /// </summary>
        public static string ContentIsRequired {
            get {
                return ResourceManager.GetString("ContentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of send.
        /// </summary>
        public static string DateOfSend {
            get {
                return ResourceManager.GetString("DateOfSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline a request to provider.
        /// </summary>
        public static string DeclineRequestToProvider {
            get {
                return ResourceManager.GetString("DeclineRequestToProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no a request with the same id !.
        /// </summary>
        public static string EixstReq {
            get {
                return ResourceManager.GetString("EixstReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give items.
        /// </summary>
        public static string GiveItems {
            get {
                return ResourceManager.GetString("GiveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is finished !.
        /// </summary>
        public static string OrderFinished {
            get {
                return ResourceManager.GetString("OrderFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order id.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Order id&quot; is required !.
        /// </summary>
        public static string OrderIdIsRequired {
            get {
                return ResourceManager.GetString("OrderIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select items !.
        /// </summary>
        public static string PleaseSelectitems {
            get {
                return ResourceManager.GetString("PleaseSelectitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider answer.
        /// </summary>
        public static string ProviderAnswer {
            get {
                return ResourceManager.GetString("ProviderAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider answers.
        /// </summary>
        public static string ProviderAnswers {
            get {
                return ResourceManager.GetString("ProviderAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider email.
        /// </summary>
        public static string ProviderEmail {
            get {
                return ResourceManager.GetString("ProviderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Provider&quot;is required !.
        /// </summary>
        public static string ProviderIsRequired {
            get {
                return ResourceManager.GetString("ProviderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove form for i tem.
        /// </summary>
        public static string RemoveFormForItem {
            get {
                return ResourceManager.GetString("RemoveFormForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for approving (Provider order).
        /// </summary>
        public static string RequestsForApproving {
            get {
                return ResourceManager.GetString("RequestsForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectItems.
        /// </summary>
        public static string SelectItems {
            get {
                return ResourceManager.GetString("SelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select organisation.
        /// </summary>
        public static string SelectOrganisation {
            get {
                return ResourceManager.GetString("SelectOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request to provider.
        /// </summary>
        public static string SendRequestToProvider {
            get {
                return ResourceManager.GetString("SendRequestToProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent email.
        /// </summary>
        public static string SentEmail {
            get {
                return ResourceManager.GetString("SentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent requests  (Provider order).
        /// </summary>
        public static string SentRequests {
            get {
                return ResourceManager.GetString("SentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will soon receive delivery.
        /// </summary>
        public static string SoonReceive {
            get {
                return ResourceManager.GetString("SoonReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Subject&quot;is required!.
        /// </summary>
        public static string SubjectIsRequired {
            get {
                return ResourceManager.GetString("SubjectIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully sent a request to provider..
        /// </summary>
        public static string SuccessSending {
            get {
                return ResourceManager.GetString("SuccessSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View approved request (Provider order).
        /// </summary>
        public static string ViewApprovedRequest {
            get {
                return ResourceManager.GetString("ViewApprovedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View history request (Provider order).
        /// </summary>
        public static string ViewHistoryRequest {
            get {
                return ResourceManager.GetString("ViewHistoryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View request for approving (Provider order).
        /// </summary>
        public static string ViewRequestForApproving {
            get {
                return ResourceManager.GetString("ViewRequestForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want items.
        /// </summary>
        public static string WantItems {
            get {
                return ResourceManager.GetString("WantItems", resourceCulture);
            }
        }
    }
}
