//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.OrdersTr.ItemOrderTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemOrderTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemOrderTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.OrdersTr.ItemOrderTr.ItemOrderTr", typeof(ItemOrderTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved items.
        /// </summary>
        public static string ApprovedItems {
            get {
                return ResourceManager.GetString("ApprovedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved request (Item order).
        /// </summary>
        public static string ApprovedRequestIO {
            get {
                return ResourceManager.GetString("ApprovedRequestIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are items for location?.
        /// </summary>
        public static string AreItemsForLocation {
            get {
                return ResourceManager.GetString("AreItemsForLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are items for user?.
        /// </summary>
        public static string AreItemsForUser {
            get {
                return ResourceManager.GetString("AreItemsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are items gave?.
        /// </summary>
        public static string AreItemsGave {
            get {
                return ResourceManager.GetString("AreItemsGave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base details.
        /// </summary>
        public static string BaseDetails {
            get {
                return ResourceManager.GetString("BaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose items.
        /// </summary>
        public static string ChooseItems {
            get {
                return ResourceManager.GetString("ChooseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose location.
        /// </summary>
        public static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose user.
        /// </summary>
        public static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create asset.
        /// </summary>
        public static string CreateAsset {
            get {
                return ResourceManager.GetString("CreateAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create assets.
        /// </summary>
        public static string CreateAssets {
            get {
                return ResourceManager.GetString("CreateAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline a request for items.
        /// </summary>
        public static string DeclineRequest {
            get {
                return ResourceManager.GetString("DeclineRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished request (Item order).
        /// </summary>
        public static string FinishedRequestIO {
            get {
                return ResourceManager.GetString("FinishedRequestIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For location.
        /// </summary>
        public static string ForLocation {
            get {
                return ResourceManager.GetString("ForLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For site.
        /// </summary>
        public static string ForSite {
            get {
                return ResourceManager.GetString("ForSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For user.
        /// </summary>
        public static string ForUser {
            get {
                return ResourceManager.GetString("ForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gave items.
        /// </summary>
        public static string GaveItems {
            get {
                return ResourceManager.GetString("GaveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give items.
        /// </summary>
        public static string GiveItems {
            get {
                return ResourceManager.GetString("GiveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item details.
        /// </summary>
        public static string ItemDetails {
            get {
                return ResourceManager.GetString("ItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items are not gave!.
        /// </summary>
        public static string ItemsAreNotGave {
            get {
                return ResourceManager.GetString("ItemsAreNotGave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Items&quot;is required !.
        /// </summary>
        public static string ItemsAreRequired {
            get {
                return ResourceManager.GetString("ItemsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items for giving.
        /// </summary>
        public static string ItemsForGiving {
            get {
                return ResourceManager.GetString("ItemsForGiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Count value is greater than permissible..
        /// </summary>
        public static string PermissableError {
            get {
                return ResourceManager.GetString("PermissableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select items.
        /// </summary>
        public static string PleaseSelectItems {
            get {
                return ResourceManager.GetString("PleaseSelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for finishing (Item order).
        /// </summary>
        public static string RequestForFinishingIO {
            get {
                return ResourceManager.GetString("RequestForFinishingIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for items.
        /// </summary>
        public static string RequestForItems {
            get {
                return ResourceManager.GetString("RequestForItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is not approved !.
        /// </summary>
        public static string RequestIsNotApproved {
            get {
                return ResourceManager.GetString("RequestIsNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for approving ( Item Order ).
        /// </summary>
        public static string RequestsForApprovingIO {
            get {
                return ResourceManager.GetString("RequestsForApprovingIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for finishing (Item order).
        /// </summary>
        public static string RequestsForFinishingIO {
            get {
                return ResourceManager.GetString("RequestsForFinishingIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive other items later !.
        /// </summary>
        public static string RequestSpecialMessage {
            get {
                return ResourceManager.GetString("RequestSpecialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotating item.
        /// </summary>
        public static string RotatingItem {
            get {
                return ResourceManager.GetString("RotatingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully sent the request !.
        /// </summary>
        public static string SeccessSending {
            get {
                return ResourceManager.GetString("SeccessSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected offers.
        /// </summary>
        public static string SelectedOffers {
            get {
                return ResourceManager.GetString("SelectedOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent offers.
        /// </summary>
        public static string SendOffers {
            get {
                return ResourceManager.GetString("SendOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are two assets with same inventory numbers !.
        /// </summary>
        public static string TwoAssets {
            get {
                return ResourceManager.GetString("TwoAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want items.
        /// </summary>
        public static string WantItems {
            get {
                return ResourceManager.GetString("WantItems", resourceCulture);
            }
        }
    }
}
