//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.ScrappingTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScrappingTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScrappingTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.ScrappingTr.ScrappingTr", typeof(ScrappingTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve scrapping request.
        /// </summary>
        public static string ApproveScrappingRequest {
            get {
                return ResourceManager.GetString("ApproveScrappingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset details.
        /// </summary>
        public static string AssetDetails {
            get {
                return ResourceManager.GetString("AssetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset inventory number.
        /// </summary>
        public static string AssetInventoryNumber {
            get {
                return ResourceManager.GetString("AssetInventoryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of manufacture.
        /// </summary>
        public static string DateOfManufacture {
            get {
                return ResourceManager.GetString("DateOfManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of send.
        /// </summary>
        public static string DateOfSend {
            get {
                return ResourceManager.GetString("DateOfSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline a request for scrapping asset.
        /// </summary>
        public static string DeclineReqForScrapping {
            get {
                return ResourceManager.GetString("DeclineReqForScrapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History requests for scrapping.
        /// </summary>
        public static string HistoryRequestsForScrapping {
            get {
                return ResourceManager.GetString("HistoryRequestsForScrapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is approved?.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history !.
        /// </summary>
        public static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests for appoving !.
        /// </summary>
        public static string NoRequestsForApproving {
            get {
                return ResourceManager.GetString("NoRequestsForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for scrapping an asset.
        /// </summary>
        public static string RequestForScrappingAnAsset {
            get {
                return ResourceManager.GetString("RequestForScrappingAnAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrapping requests for approving.
        /// </summary>
        public static string ScrappingReqsForApproving {
            get {
                return ResourceManager.GetString("ScrappingReqsForApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrapping request.
        /// </summary>
        public static string ScrappingRequest {
            get {
                return ResourceManager.GetString("ScrappingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully sent a request for scrapping of an asset..
        /// </summary>
        public static string SuccessfullySent {
            get {
                return ResourceManager.GetString("SuccessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset was scrapped !.
        /// </summary>
        public static string TheAssetWasScrapped {
            get {
                return ResourceManager.GetString("TheAssetWasScrapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a request for scrapping of this asset.
        /// </summary>
        public static string ThereIsRequestForScrapping {
            get {
                return ResourceManager.GetString("ThereIsRequestForScrapping", resourceCulture);
            }
        }
    }
}
