//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.AdminArea {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.AdminArea.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new user.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new security group.
        /// </summary>
        public static string AddSecGroup {
            get {
                return ResourceManager.GetString("AddSecGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked users.
        /// </summary>
        public static string BlockedUsers {
            get {
                return ResourceManager.GetString("BlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Name&quot; is required..
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No blocked users !.
        /// </summary>
        public static string NoBlUsers {
            get {
                return ResourceManager.GetString("NoBlUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select organisation and site or nothing !.
        /// </summary>
        public static string OrgOrNothing {
            get {
                return ResourceManager.GetString("OrgOrNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security groups.
        /// </summary>
        public static string SecGroups {
            get {
                return ResourceManager.GetString("SecGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        public static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a organisation.
        /// </summary>
        public static string SelectOrganisation {
            get {
                return ResourceManager.GetString("SelectOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a site.
        /// </summary>
        public static string SelectSite {
            get {
                return ResourceManager.GetString("SelectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are security group with the same name !.
        /// </summary>
        public static string ThereAreSecGroup {
            get {
                return ResourceManager.GetString("ThereAreSecGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add group with this name !.
        /// </summary>
        public static string YouCantAddSameName {
            get {
                return ResourceManager.GetString("YouCantAddSameName", resourceCulture);
            }
        }
    }
}
