//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.AdminArea {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rights {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rights() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.AdminArea.Rights", typeof(Rights).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super admin. The user has full access.
        /// </summary>
        public static string n1 {
            get {
                return ResourceManager.GetString("n1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can approve request for scrapping an asset...
        /// </summary>
        public static string n10 {
            get {
                return ResourceManager.GetString("n10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can send request for relocation..
        /// </summary>
        public static string n11 {
            get {
                return ResourceManager.GetString("n11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can approve request for relocation..
        /// </summary>
        public static string n12 {
            get {
                return ResourceManager.GetString("n12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can send request for renovation..
        /// </summary>
        public static string n13 {
            get {
                return ResourceManager.GetString("n13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can approve request for renovation..
        /// </summary>
        public static string n14 {
            get {
                return ResourceManager.GetString("n14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can renovate assets..
        /// </summary>
        public static string n15 {
            get {
                return ResourceManager.GetString("n15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can add, edit and delete providers..
        /// </summary>
        public static string n16 {
            get {
                return ResourceManager.GetString("n16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can create order for asset..
        /// </summary>
        public static string n17 {
            get {
                return ResourceManager.GetString("n17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can approve orders for asset..
        /// </summary>
        public static string n18 {
            get {
                return ResourceManager.GetString("n18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can give items for asset order..
        /// </summary>
        public static string n19 {
            get {
                return ResourceManager.GetString("n19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can add, remove and edit organisations..
        /// </summary>
        public static string n2 {
            get {
                return ResourceManager.GetString("n2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can send request to provider for items..
        /// </summary>
        public static string n20 {
            get {
                return ResourceManager.GetString("n20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can Approve request to provider for items..
        /// </summary>
        public static string n21 {
            get {
                return ResourceManager.GetString("n21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can add ad edit currency..
        /// </summary>
        public static string n22 {
            get {
                return ResourceManager.GetString("n22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can add and change exchange rates..
        /// </summary>
        public static string n23 {
            get {
                return ResourceManager.GetString("n23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can create invoices..
        /// </summary>
        public static string n24 {
            get {
                return ResourceManager.GetString("n24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can approve invoices..
        /// </summary>
        public static string n25 {
            get {
                return ResourceManager.GetString("n25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can pay invoices..
        /// </summary>
        public static string n26 {
            get {
                return ResourceManager.GetString("n26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can answer queries from other users on the system..
        /// </summary>
        public static string n27 {
            get {
                return ResourceManager.GetString("n27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can create report for assets by status..
        /// </summary>
        public static string n28 {
            get {
                return ResourceManager.GetString("n28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can create report for accidents by status..
        /// </summary>
        public static string n29 {
            get {
                return ResourceManager.GetString("n29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can add, remove and edit sites in organisation..
        /// </summary>
        public static string n3 {
            get {
                return ResourceManager.GetString("n3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can create report for invoice by creation, approving and payment date and other fields..
        /// </summary>
        public static string n30 {
            get {
                return ResourceManager.GetString("n30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can create report about all relocations for certain asset..
        /// </summary>
        public static string n31 {
            get {
                return ResourceManager.GetString("n31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can create report about all renovated assets between two dates..
        /// </summary>
        public static string n32 {
            get {
                return ResourceManager.GetString("n32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user manages organisation, sites, users and security groups..
        /// </summary>
        public static string n33 {
            get {
                return ResourceManager.GetString("n33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can add, remove and edit items in application..
        /// </summary>
        public static string n4 {
            get {
                return ResourceManager.GetString("n4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can edit, add assets, send request for scrapping.
        /// </summary>
        public static string n5 {
            get {
                return ResourceManager.GetString("n5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can add, remove and edit items in location..
        /// </summary>
        public static string n6 {
            get {
                return ResourceManager.GetString("n6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can create a order for item..
        /// </summary>
        public static string n7 {
            get {
                return ResourceManager.GetString("n7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can approve orders for item..
        /// </summary>
        public static string n8 {
            get {
                return ResourceManager.GetString("n8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user can give items  for item order.
        /// </summary>
        public static string n9 {
            get {
                return ResourceManager.GetString("n9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin right.
        /// </summary>
        public static string r1 {
            get {
                return ResourceManager.GetString("r1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve request for scrapping.
        /// </summary>
        public static string r10 {
            get {
                return ResourceManager.GetString("r10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request for relocation.
        /// </summary>
        public static string r11 {
            get {
                return ResourceManager.GetString("r11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve request for relocation.
        /// </summary>
        public static string r12 {
            get {
                return ResourceManager.GetString("r12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request for renovation.
        /// </summary>
        public static string r13 {
            get {
                return ResourceManager.GetString("r13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve request for renovation.
        /// </summary>
        public static string r14 {
            get {
                return ResourceManager.GetString("r14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovate assets.
        /// </summary>
        public static string r15 {
            get {
                return ResourceManager.GetString("r15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage providers.
        /// </summary>
        public static string r16 {
            get {
                return ResourceManager.GetString("r16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create order for asset.
        /// </summary>
        public static string r17 {
            get {
                return ResourceManager.GetString("r17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve orders for asset.
        /// </summary>
        public static string r18 {
            get {
                return ResourceManager.GetString("r18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give assets for asset orders.
        /// </summary>
        public static string r19 {
            get {
                return ResourceManager.GetString("r19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage organisation.
        /// </summary>
        public static string r2 {
            get {
                return ResourceManager.GetString("r2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request to provider.
        /// </summary>
        public static string r20 {
            get {
                return ResourceManager.GetString("r20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve request to provider.
        /// </summary>
        public static string r21 {
            get {
                return ResourceManager.GetString("r21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage currency.
        /// </summary>
        public static string r22 {
            get {
                return ResourceManager.GetString("r22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage exchange rates.
        /// </summary>
        public static string r23 {
            get {
                return ResourceManager.GetString("r23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create invoice.
        /// </summary>
        public static string r24 {
            get {
                return ResourceManager.GetString("r24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve invoice.
        /// </summary>
        public static string r25 {
            get {
                return ResourceManager.GetString("r25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay invoice.
        /// </summary>
        public static string r26 {
            get {
                return ResourceManager.GetString("r26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responding to incidents.
        /// </summary>
        public static string r27 {
            get {
                return ResourceManager.GetString("r27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for assets by status.
        /// </summary>
        public static string r28 {
            get {
                return ResourceManager.GetString("r28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for accidents by date.
        /// </summary>
        public static string r29 {
            get {
                return ResourceManager.GetString("r29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage site.
        /// </summary>
        public static string r3 {
            get {
                return ResourceManager.GetString("r3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for invoices by date.
        /// </summary>
        public static string r30 {
            get {
                return ResourceManager.GetString("r30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for asset relocations.
        /// </summary>
        public static string r31 {
            get {
                return ResourceManager.GetString("r31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for renovated assets.
        /// </summary>
        public static string r32 {
            get {
                return ResourceManager.GetString("r32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low admin.
        /// </summary>
        public static string r33 {
            get {
                return ResourceManager.GetString("r33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage items.
        /// </summary>
        public static string r4 {
            get {
                return ResourceManager.GetString("r4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage assets.
        /// </summary>
        public static string r5 {
            get {
                return ResourceManager.GetString("r5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage locations.
        /// </summary>
        public static string r6 {
            get {
                return ResourceManager.GetString("r6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create order for item.
        /// </summary>
        public static string r7 {
            get {
                return ResourceManager.GetString("r7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve order for item.
        /// </summary>
        public static string r8 {
            get {
                return ResourceManager.GetString("r8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give items for item order.
        /// </summary>
        public static string r9 {
            get {
                return ResourceManager.GetString("r9", resourceCulture);
            }
        }
    }
}
