//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAssets.Resources.Translation.RelocationTr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RelocationTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RelocationTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAssets.Resources.Translation.RelocationTr.RelocationTr", typeof(RelocationTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprove request for relocation of asset.
        /// </summary>
        public static string ApproveRequestForRelocation {
            get {
                return ResourceManager.GetString("ApproveRequestForRelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;Asset&quot;is required..
        /// </summary>
        public static string AssetIsRequired {
            get {
                return ResourceManager.GetString("AssetIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose asset.
        /// </summary>
        public static string ChooseAsset {
            get {
                return ResourceManager.GetString("ChooseAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose location.
        /// </summary>
        public static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose site.
        /// </summary>
        public static string ChooseSite {
            get {
                return ResourceManager.GetString("ChooseSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose user.
        /// </summary>
        public static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create relocation request.
        /// </summary>
        public static string CreateRelocationReq {
            get {
                return ResourceManager.GetString("CreateRelocationReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline a request for relocation.
        /// </summary>
        public static string DeclineRequestForRelocation {
            get {
                return ResourceManager.GetString("DeclineRequestForRelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From location.
        /// </summary>
        public static string FromLocation {
            get {
                return ResourceManager.GetString("FromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From site.
        /// </summary>
        public static string FromSite {
            get {
                return ResourceManager.GetString("FromSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From user.
        /// </summary>
        public static string FromUser {
            get {
                return ResourceManager.GetString("FromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History requests for relocation.
        /// </summary>
        public static string HistoryRequestsForRelocation {
            get {
                return ResourceManager.GetString("HistoryRequestsForRelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests !.
        /// </summary>
        public static string NoRequests {
            get {
                return ResourceManager.GetString("NoRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive asset.
        /// </summary>
        public static string ReceiveAsset {
            get {
                return ResourceManager.GetString("ReceiveAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocation request.
        /// </summary>
        public static string RelocationRequest {
            get {
                return ResourceManager.GetString("RelocationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for issue asset with user.
        /// </summary>
        public static string RequestForGivingAssetWithUser {
            get {
                return ResourceManager.GetString("RequestForGivingAssetWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for issue of asset.
        /// </summary>
        public static string RequestForIssueOfAsset {
            get {
                return ResourceManager.GetString("RequestForIssueOfAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for receiving asset without user.
        /// </summary>
        public static string RequestForReceivingAssetWithoutUser {
            get {
                return ResourceManager.GetString("RequestForReceivingAssetWithoutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for receving asset with user.
        /// </summary>
        public static string RequestForReceivingAssetWithUser {
            get {
                return ResourceManager.GetString("RequestForReceivingAssetWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for issue without user.
        /// </summary>
        public static string RequestsForIssueWithoutUser {
            get {
                return ResourceManager.GetString("RequestsForIssueWithoutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for issue with user.
        /// </summary>
        public static string RequestsForIssueWithUser {
            get {
                return ResourceManager.GetString("RequestsForIssueWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for receiving without user.
        /// </summary>
        public static string RequestsForReceivingWithoutUser {
            get {
                return ResourceManager.GetString("RequestsForReceivingWithoutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for receiving with user.
        /// </summary>
        public static string RequestsForReceivingWithUser {
            get {
                return ResourceManager.GetString("RequestsForReceivingWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully sent a request for relocation of an asset..
        /// </summary>
        public static string SuccessSending {
            get {
                return ResourceManager.GetString("SuccessSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is request for relocation of this asset..
        /// </summary>
        public static string ThereIsRequest {
            get {
                return ResourceManager.GetString("ThereIsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To location.
        /// </summary>
        public static string ToLocation {
            get {
                return ResourceManager.GetString("ToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To site.
        /// </summary>
        public static string ToSite {
            get {
                return ResourceManager.GetString("ToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;To site&quot; is required..
        /// </summary>
        public static string ToSiteIsRequired {
            get {
                return ResourceManager.GetString("ToSiteIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To user.
        /// </summary>
        public static string ToUser {
            get {
                return ResourceManager.GetString("ToUser", resourceCulture);
            }
        }
    }
}
